name: github-actions
on:
  push:
  pull_request:
  workflow_dispatch:
    branches:
      - openapi

jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: ./build