name: github-actions
on: [push]
jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.19.1
      - run: ./build